import { AnimationConfiguration } from "./AnimationHandler";

const none: AnimationConfiguration = {
  animationConfiguration: {
    duration: 0
  },
  attachAnimationStartState: {},
  attachAnimationEndState: {},
  detachAnimationStartState: {},
  detachAnimationEndState: {},
  showAnimationStartState: {},
  showAnimationEndState: {},
  hideAnimationStartState: {},
  hideAnimationEndState: {}
}

export default none