# This file was generated by RNOH autolinking.
# DO NOT modify it manually, your changes WILL be overwritten.
cmake_minimum_required(VERSION 3.5)

# @api
function(autolink_libraries target)

    set(AUTOLINKED_LIBRARIES
    )

    foreach(lib ${AUTOLINKED_LIBRARIES})
        target_link_libraries(${target} PUBLIC ${lib})
    endforeach()
endfunction()
